name: Generate Snake

on:
  schedule:
    - cron: "0 18 * * *"   # runs daily at 18:00 UTC
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: BheemeshGundikeri   # <-- your username
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Commit SVGs to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "chore: update snake" || echo "no changes"
          git push
